### ISSUE TITLE
[PE-D][Tester E] Error message given for editing bolt incorrect

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-4/tp#104]
When an invalid bolt number is given, i.e. `edit 1 b/-1`, the error message shown is `Bolts given should be a positive integer between 1 and 10.`

However, you are able to set bolts to 0, i.e. `edit 1 b/0`.

This might confuse users that want to set bolts to 0 but thought the app is unable to do so.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: darkvoid32/ped#2

**Comment by kwuunnn** [comment]
#146 Fixes this
