### ISSUE TITLE
[PE-D][Tester B] Multiple valid values with prefix s/ falls through in the star command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-4/tp#107]
The following erroneous input falls through the program with no warnings or error displayed
`star 3 s/3 s/4 s/5`. Which gives the incorrect output of the last prefix. 
The same applies to a command of random or descending order like `star 3 s/6 s/5 s/4 `.
Output of `star 3 s/3 s/4 s/5`:
Before:
![Star erronous input .png](https://raw.githubusercontent.com/Pluiexo/ped/main/files/49ba226d-dda5-4974-a1dd-5e92f56659c6.png)

After:
![Star erronous output.png](https://raw.githubusercontent.com/Pluiexo/ped/main/files/aa830aa4-5693-461a-819d-9e4ba0ce4f3c.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Pluiexo/ped#2

**Comment by chiaryan** [comment]
Same reason as #109
