### ISSUE TITLE
[PE-D][Tester E] `add` command outdated for quickstart

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F13-4/tp#127]
`add` command still uses `AddressBook` command in quickstart

![Capture.PNG](https://raw.githubusercontent.com/darkvoid32/ped/main/files/639f31b1-5ee8-409a-8a5a-2f38da98ee7a.PNG)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: darkvoid32/ped#9

**Comment by chiaryan** [comment]
Duplicate of #113
