### ISSUE TITLE
[PE-D][Tester A] Help command user guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F13-4/tp#97]
![Screenshot 2024-04-05 at 4.12.06 PM.png](https://raw.githubusercontent.com/KinTatHo/ped/main/files/fecff67c-21d5-4361-be9f-d740c9bf4b4f.png)
Not the same as the one on the UserGuide:
![Screenshot 2024-04-05 at 4.14.00 PM.png](https://raw.githubusercontent.com/KinTatHo/ped/main/files/064c6b3e-0bdd-48d4-8be5-c777317ee951.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: KinTatHo/ped#1

**Comment by chiaryan** [comment]
Same as #98
